import type { CollectionConfig } from 'payload'
import { allowOnlyAdmin } from '../../access/allowOnlyAdmin'
import { anyone } from '../../access/anyone'

/**
 * Caches AI-interpreted queries so the same informal phrasing does not
 * trigger a new OpenAI call every time.
 *
 * Delete a document to force re-interpretation on the next search.
 */
export const EscoQueryCache: CollectionConfig = {
  slug: 'esco-query-cache',
  admin: {
    useAsTitle: 'input',
    group: 'ESCO',
    defaultColumns: ['input', 'detectedLanguage', 'expiresAt', 'updatedAt'],
    description: 'Cached AI-interpreted occupation search queries. Delete to invalidate.',
  },
  access: {
    read: anyone,
    create: allowOnlyAdmin,
    update: allowOnlyAdmin,
    delete: allowOnlyAdmin,
  },
  fields: [
    {
      name: 'inputHash',
      type: 'text',
      required: true,
      unique: true,
      admin: {
        description: 'SHA-256 of the normalised input used as cache key.',
      },
    },
    {
      name: 'input',
      type: 'text',
      required: true,
      admin: {
        description: 'Original (normalised) candidate input.',
      },
    },
    {
      name: 'detectedLanguage',
      type: 'text',
      required: false,
    },
    {
      name: 'searchTerms',
      type: 'json',
      required: true,
      admin: {
        description: 'Array of ESCO-compatible search terms generated by the AI.',
      },
    },
    {
      name: 'expiresAt',
      type: 'date',
      required: true,
      admin: {
        description: 'Cache expiry date (default 30 days from creation).',
      },
    },
  ],
}
